version: '3'

services:
  server:
    image: node:latest
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"

  client:
    image: node:latest
    volumes:
      - ./client:/app
    working_dir: /app
    ports:
      - "${PORT:-7000}:${PORT:-7000}"
    env_file:
      - ./client/.env
    command: sh -c "npm install && npm run start"

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - "4551:4551"
    env_file:
      - ./client/.env
    links:
      - client
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DOMAIN=client
      - PORT=${PORT:-7000}